#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/works
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir target
            curl -sLo target/builder toast.sh/builder
            bash ./target/builder
      - persist_to_workspace:
          root: ~/works
          paths:
            - .
  release:
    docker:
      - image: circleci/golang
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Release
          command: |
            bash ./target/builder
  slack:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Slack
          command: |
            bash ./target/builder

# Advanced Settings
# - Build forked pull requests
# - Pass secrets to builds from forked pull requests
# - Only build pull requests

workflows:
  version: 2
  apply:
    jobs:
      - build
      - release:
          requires:
            - build
      - slack:
          requires:
            - release
